### ISSUE TITLE
Differences between code reproduction and paper results

### ISSUE THREAD

**Issue by jian-rookie** [billpsomas/rscir#3]
I reproduce the latest code on the proposed dataset in your paper. But the AP of Category Existence is different from that of the paper.
All results of my  code reproduction are shown as follows.
![clip](https://github.com/user-attachments/assets/9a86b7da-eb99-4409-9ecf-1098abd09cfa)
![remoteclip](https://github.com/user-attachments/assets/9e334936-cc33-490f-8cf2-f8c3427fb260)

I wonder if you recently updated the dataset and I didn't download the latest version. Or is there some other reason?
Hope for your reply.

**Comment by billpsomas** [comment]
Hello @jian-rookie,

I am currently out of the lab, so I will respond as soon as I am back. Sorry for the delay!

Thanks

**Comment by billpsomas** [comment]
Hello again @jian-rookie,

Hope my e-mail finds you well. 

You are actually right. Your 'existence' results are correct. They are the ones corresponding to the current version of the dataset. The other results were probably of our older version.

So, your Table is correct. Feel free to use it on your work/paper.

Thanks a lot for pointing this out.
