### ISSUE TITLE
Details of CLIP weight

### ISSUE THREAD

**Issue by jian-rookie** [billpsomas/rscir#5]
Can you provide more detailed information of CLIP weight？Is the CLIP weight released by OpenAI or OpenCLIP? If the weight is provided by OpenCLIP, is the CLIP weight trained on LAION-2B or DataComp-1B?

**Comment by billpsomas** [comment]
Hello @jian-rookie,

I am out of the lab, but if I remember correctly, it's from OpenCLIP the one shown in attached image.![IMG_20240819_100607.jpg](https://github.com/user-attachments/assets/659a52cb-eb7a-4001-a157-0c719fceeacf)
